### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by sadi-guzel** [ayoolaolafenwa/PixelLib#37]
I use `cudav11.0` and `tensorflow-2.4.1` and I got out of memory error both for testing and training code with `batch_size = 1`

following configuration did not also solve the problem
```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto(allow_soft_placement=True)
config.gpu_options.allow_growth = True
# config.gpu_options.per_process_gpu_memory_fraction = 0.33
session = InteractiveSession(config=config)
```

**Comment by ayoolaolafenwa** [comment]
@sadi-guzel PixelLib works with well with tensorflow 2.4.1. Depending on the GPU capacity of a PC I recommended a batch size of 1 e.g a PC with a 4G RAM GPU would support a batch size of 1 for  resnet50 or resnet101.  
I would like to have more information  like the number of images you are training and their resolutions?
If the GPU capacity of your PC is low you could consider using google colab where you would have access to a single 12GB NVIDIA Tesla K80 GPU.

**Comment by sadi-guzel** [comment]
**nvidia-smi**
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 457.09       Driver Version: 457.09       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+====================|
|   0  **GeForce GTX 1050**   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8    N/A /  N/A |     68MiB /  **2048MiB** |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**test -code(with resnet50):**
```
import pixellib
from pixellib.instance import custom_segmentation
import time
segment_image = custom_segmentation()
segment_image.inferConfig(network_backbone="resnet50", num_classes= 3, class_names= ["BG", "carrot", "onion", "herbal_powder"])
segment_image.load_model("mask_rcnn_products_models/mask_rcnn_model.009-0.249542.h5")
start = time.time()
segment_image.segmentImage("products/test_images/ACD88F4D-92F7-48D9-A56A-B3AB0BBA326D.jpeg", show_bboxes=True, output_image_name="products/sample_out.jpg")
print(f'elapsed: {(time.time() - start) * 1000} ms')
```

**tensorflow==2.4.1**
**cuda_11.0.3**
**cudnn-11.0-windows-x64-v8.0.5.39**
**max image size = 460X345**

Segmenting image still lasts more than 2 seconds. Is it because of cuda and cdnn versions, or can creating a conda environment solve the problem? Please help :)

**Comment by ayoolaolafenwa** [comment]
@sadi-guzel  The Cuda and CuDNN versions have nothing to do with inference speed. If you want to determine the actual inference speed you have to do it differently and you could not get the actual time by processing just a single image. 
The first image that would be processed takes a longer time,  because of the initialization of the  GPU, once it is initialized the time required for processing other images would be smaller.
You should add more images after the first image  and print the time required for each of the images processed after the first image. 

**Note**: You saved the processed image, if you want to get the actual time used to segment the image you would not save the image. This is because the time required to save the image would also be added to the inference time. If you want to get the actual inference time just process the images directly without saving it.  
*Modified code* 
 
```python
 import pixellib
from pixellib.instance import custom_segmentation
import time


segment_image = custom_segmentation()
segment_image.inferConfig(network_backbone="resnet50", num_classes= 3, class_names= ["BG", "carrot", "onion", "herbal_powder"])
segment_image.load_model("mask_rcnn_products_models/mask_rcnn_model.009-0.249542.h5")

#start = time.time()
segment_image.segmentImage("products/test_images/ACD88F4D-92F7-48D9-A56A-B3AB0BBA326D.jpeg", show_bboxes=True)
#print(f'elapsed: {(time.time() - start) * 1000} ms')

start = time.time()
segment_image.segmentImage("sample2.jpg", show_bboxes=True)
print(f'elapsed: {(time.time() - start) * 1000} ms')

start = time.time()
segment_image.segmentImage("sample3.jpg", show_bboxes=True)
print(f'elapsed: {(time.time() - start) * 1000} ms')

start = time.time()
segment_image.segmentImage("sample4.jpg", show_bboxes=True)
print(f'elapsed: {(time.time() - start) * 1000} ms')
```

In the modified code above I added three more images after the first image, commented the *print inference speed for the first image* because it included the time added during GPU  initialization.  I printed the inference time of the added image and did not save them in order to get the actual inference speed without including the time required to save them.
